#!/bin/bash

if [[ -f "./env.sh"]]; then
   echo "Используй переменные окружения из ${PWD}/env.sh"
   source ./env.sh
fi

workDir="${WORKING_DIRECTORY=~/Workspace}"

help() {
     echo "
     Usage: 
        ./application init - создание рабочей директории и базы данных.
        ./applicarion clean - очищение рабочей директории.
        ./application buid - запускает JUnit тесты для проверки работоспсобности приложения(-skipTests Чтобы пропустить тесты)
         и билдит джар.
        ./application up - запуск приложения.
    "
}

init() {
# Создание рабочей директории
     mkdir -p "${workDir}"
    cd "${workDir}" || exit

# git clone
  if [[ ! -d "spring-starter" ]]; then
      git clone https://github.com/dmdev2020/spring-starter.git
  fi 
  cd "spring-starter" || exit
  git checkout lesson-125

# PostgresSQL
  



}







case $1 in
help)
      help
      ;;
init)
      init
      ;;
*)
      echo "$1 Команда не доступна"
      ;;
esac
